#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
exec="../../../bin/prepareCase.sh"

if [ -x "$exec" ]
then
    . $exec
else
    echo "The file $WAVES_DIR/bin/prepareCase.sh is not executable."
    echo "Make the file executable before continuing."
    echo
    echo "Exiting tutorial case."
    exit 1
fi


# Set application name
application="waveFoam"

# Create the wave probes
runApplication waveGaugesNProbes

# Set wave parameters
runApplication setWaveParameters

# Set wave field
runApplication setWaveField

# Run application
#runApplication decomposePar

#runParallel $application 64

#runApplication reconstructPar

# To a post-processing analysis
#runApplication postProcessWaves2Foam
sample

./boundaryDataTransfer_pd
